# Generated by Django 3.1.7 on 2021-02-23 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.BinaryField(default=b'\xb0\x16(\xff\xc2<x\x8aA\xaa=\xda\x92\x9f#}\xc0!o\xc3?\x86K\xacd\x9f\xfa\x81|9>\xdc', verbose_name='SALT')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='slug')),
                ('publisher', models.ForeignKey(default=1, help_text='Publisher', on_delete=django.db.models.deletion.DO_NOTHING, to='fiveapp.user')),
            ],
        ),
    ]
