# Generated by Django 3.1.7 on 2021-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0002_user_register_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salt',
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.BinaryField(default=b'Z\xc6\xd5\x82', verbose_name='SALT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(verbose_name='Registered At'),
        ),
    ]
