# Generated by Django 3.1.7 on 2021-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0003_auto_20210225_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.BinaryField(verbose_name='SALT'),
        ),
    ]
