# Generated by Django 3.1.7 on 2021-03-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20210309_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='request_accepted',
            field=models.BooleanField(default=False, verbose_name='Request Accepted'),
        ),
    ]
