# Generated by Django 3.1.7 on 2021-03-17 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_follow_request_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.                                  Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
