# Generated by Django 3.1.7 on 2021-03-26 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20210317_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09121234567'.                                  exactly 11 digits allowed.", regex='09[0-3][0-9]-?[0-9]{3}-?[0-9]{4}')]),
        ),
    ]
