# Generated by Django 3.1.7 on 2021-03-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20210326_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='token',
        ),
        migrations.AddField(
            model_name='member',
            name='sms_code',
            field=models.CharField(default='0', max_length=4, verbose_name='Sms Code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superuser'),
        ),
    ]
