# Generated by Django 3.1.7 on 2021-03-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20210331_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sms_code',
            field=models.CharField(max_length=4, verbose_name='Sms Code'),
        ),
    ]
