# Generated by Django 3.1.7 on 2021-04-02 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='eventfollowrequest',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='eventlike',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='eventlike',
            name='post',
        ),
        migrations.AddField(
            model_name='event',
            name='foreign_key',
            field=models.IntegerField(blank=True, null=True, verbose_name="Post Or Comment's Id"),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'like'), ('follow', 'follow'), ('accept', 'accept')], default='like', max_length=7, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to=settings.AUTH_USER_MODEL, verbose_name='Viewer'),
        ),
        migrations.DeleteModel(
            name='EventAcceptFollow',
        ),
        migrations.DeleteModel(
            name='EventComment',
        ),
        migrations.DeleteModel(
            name='EventFollowRequest',
        ),
        migrations.DeleteModel(
            name='EventLike',
        ),
    ]
