# Generated by Django 3.1.7 on 2021-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210402_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'like'), ('follow', 'follow'), ('accept', 'accept')], max_length=7, verbose_name='Type'),
        ),
    ]
