# Generated by Django 3.1.7 on 2021-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0002_auto_20210302_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(help_text='liked by', to='user.User'),
        ),
    ]
