# Generated by Django 3.1.7 on 2021-02-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('publish_date', models.DateTimeField(verbose_name='Publish Date')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='slug')),
                ('liked', models.ManyToManyField(help_text='liked by', related_name='liked', to='user.User')),
                ('publisher', models.ForeignKey(help_text='Publisher', on_delete=django.db.models.deletion.DO_NOTHING, related_name='publisher', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('publish_date', models.DateTimeField(verbose_name='Publish Date')),
                ('post', models.ForeignKey(help_text='Post', on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('publisher', models.ForeignKey(help_text='Publisher', on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
