# Generated by Django 3.1.7 on 2021-02-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('register_time', models.DateTimeField(verbose_name='Registered At')),
                ('salt', models.BinaryField(verbose_name='SALT')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(help_text='follower', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='user.user')),
                ('following', models.ForeignKey(help_text='following', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user.user')),
            ],
        ),
    ]
